### ISSUE TITLE
Compiled ahk exe does not start in intended method

### ISSUE THREAD

**Issue by CoffeeCoder1015** [Jimmysaaan/AGS-library-reserve-processor#2]
# Compiled ahk exe does not start in intended method
expected behavior: ahk script runs in background when exe file is clicked on

## How it actually starts
Compiled exe only starts when executed through powershell
```powershell
& '.\AGS.Library.reserve.processor.v0.3 (1).exe'
```

**Comment by Jimmysaaan** [comment]
The issue seems to be a false positive from windows defender

**Comment by Jimmysaaan** [comment]
> The issue seems to be a false positive from windows defender

This is probably not the case

I also can't seem to reproduce the issue

**Comment by CoffeeCoder1015** [comment]
Circumvent windows security measures by building source
